sudo: false

language: haskell

addons:
 apt:
  sources:
   - llvm-toolchain-precise-3.5
   - ubuntu-toolchain-r-test
  packages:
   - gcc-4.8
   - g++-4.8
   - libedit-dev
   - llvm-3.5-dev

ghc:
 - 7.8

compiler:
 - gcc-4.8

before_install:
  - echo 'int main(int argc, char **argv) { return 0; }' >foo.cc
  - gcc -v -std=c++11 foo.cc -o foo
  - g++ -v -std=c++11 foo.cc -o foo
  - mkdir -p ${HOME}/choices/bin
  - ln -s /usr/bin/gcc-4.8 ${HOME}/choices/bin/gcc
  - ln -s /usr/bin/g++-4.8 ${HOME}/choices/bin/g++
  - export PATH=${HOME}/choices/bin:${PATH}
  - gcc -v -std=c++11 foo.cc -o foo
  - g++ -v -std=c++11 foo.cc -o foo

install:
  - cabal install --only-dependencies --enable-tests --force-reinstall llvm-general-pure/ llvm-general/

script:
  - cabal install --enable-tests llvm-general-pure/ llvm-general/
