sudo: false

language: haskell

addons:
 apt:
  sources:
   - llvm-toolchain-precise-3.5
   - ubuntu-toolchain-r-test
  packages:
   - gcc-4.8
   - g++-4.8
   - gcc-5
   - g++-5
   - libedit-dev
   - llvm-3.5-dev

ghc:
 - 7.8

compiler:
 - gcc-4.8

env:
  - LLVM_GENERAL_GCC_VERSION="gcc-4.8"

before_install:
  - env
  - echo 'int main(int argc, char **argv) { return 0; }' >foo.cc
  - mkdir -p ${HOME}/choices/bin
  - ln -s /usr/bin/${LLVM_GENERAL_GCC_VERSION} ${HOME}/choices/bin/gcc
  - export PATH=${HOME}/choices/bin:${PATH}
  - gcc -v -std=c++11 foo.cc -o foo
  - ${CC} -v -std=c++11 foo.cc -o foo  

install:
  - cabal install --with-cc=${CC} --only-dependencies --enable-tests --force-reinstall llvm-general-pure/ llvm-general/

script:
  - cabal install --with-cc=${CC} --enable-tests llvm-general-pure/ llvm-general/
