sudo: false

language: haskell

addons:
 apt:
  sources:
   - llvm-toolchain-precise-3.5
   - ubuntu-toolchain-r-test
  packages:
   - gcc-4.8
   - g++-4.8
   - libedit-dev
   - llvm-3.5-dev

ghc:
 - 7.8

env:
  - CC="gcc-4.8"

before_install:
  - env
  - echo 'int main(int argc, char **argv) { return 0; }' >foo.cc
  - ${CC} -v -std=c++11 foo.cc -o foo  

install:
  - cabal install --only-dependencies --enable-tests --force-reinstall llvm-general-pure/ llvm-general/

script:
  - cabal install --with-gcc=${CC} --gcc-options="-v" --enable-tests llvm-general-pure/ llvm-general/
