sudo: false

language: haskell

addons:
 apt:
  sources:
   - llvm-toolchain-precise-3.5
   - ubuntu-toolchain-r-test
  packages:
   - gcc-4.8
   - g++-4.8
   - gcc-5
   - g++-5
   - libedit-dev
   - llvm-3.5-dev

ghc:
 - 7.8

env:
  - CC="gcc-4.8" CI_FLAG="" CS_FLAG=""
  - CC="gcc-4.8" CI_FLAG="--with-cc=gcc-4.8" CS_FLAG="--with-cc=gcc-4.8"
  - CC="gcc-4.8" CI_FLAG="" CS_FLAG="--with-cc=gcc-4.8"
  - CC="gcc-4.8" CI_FLAG="--with-gcc=gcc-4.8" CS_FLAG="--with-gcc=gcc-4.8"  

before_install:
  - env
  - echo 'int main(int argc, char **argv) { return 0; }' >foo.cc
  - ${CC} -v -std=c++11 foo.cc -o foo  

install:
  - cabal install ${CI_FLAG} --only-dependencies --enable-tests --force-reinstall llvm-general-pure/ llvm-general/

script:
  - cabal install ${CS_FLAG} --enable-tests llvm-general-pure/ llvm-general/
