sudo: false

language: haskell

addons:
 apt:
  sources:
   - llvm-toolchain-precise-3.5
   - ubuntu-toolchain-r-test
  packages:
   - llvm-3.5-dev

ghc:
 - 7.10

install:
  - cabal install --only-dependencies --enable-tests --force-reinstall llvm-general-pure/ llvm-general/

script:
  - cabal install --enable-tests llvm-general-pure/ llvm-general/
